language: python

python:
    - 3.6.3

services:
    - postgresql

env:
    global:
        - APP_SETTINGS ='testing'

install:
    - pip install -r requirements.txt
    - pip install pytest-cov

before_script:
    - "psql -c 'create database ireportcorruption;' -U postgres"

script:
    - py.test --cov=app tests/
    - coverage report

after_success:
    - coveralls